#- name: Enable video core i2 dtoverlay
#  lineinfile:
#    state: present
#    path: /boot/config.txt
#    line: "dtparam=i2c_vc=on"
#    regexp: "dtparam=i2c_vc=on"

- name: Install picamera 2
  apt:
    state: present
    name: "{{ item }}"
    install_recommends: no
  with_items:
    - python3-picamera2
    - vlc
